---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hartnett.
--- DateTime: 2019/11/10 20:29
---

local string = string
local core = require("apisix.core")

local function get_username_from_basic_auth(basic_auth)
    local username = ""
    local basic_auth = basic_auth or ""
    local auth = string.gsub(basic_auth, "Basic ", "")

    local user_pass = ngx.decode_base64(auth)
    local table_user = core.strings.split(user_pass, ":")
    if #table_user > 0 then
        username = table_user[1]
    end

    return username
end

local _M = {
    get_username_from_basic_auth = get_username_from_basic_auth,
}

return _M