---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hartnett.
--- DateTime: 2019/11/8 16:45
---

local core = require("apisix.core")

-- wbxml json string to  table
-- MIX 2||imei||MIX 2||+phone_num||中国联通 (46001)
local function wbxml2info(wbxml)
    local info = {}
    if #wbxml > 10 then
        info = core.json.decode(wbxml)
    end
    return info
end

-- 获取客户端的类型
local function get_client_type(ctx)
    local ua = ""
    local user_agent = core.request.header(ctx, "user-agent")
    local table_ua = core.strings.split(user_agent, "/")

    if #table_ua > 0 then
        ua = table_ua[1]
    end

    return ua
end


-- 获取客户端的真实IP
local function get_user_srcip(ctx)
    local ip = core.request.get_ip(ctx)
    return ip
end

local _M = {
    wbxml2info = wbxml2info,
    get_user_srcip = get_user_srcip,
    get_client_type = get_client_type,
}

return _M
